<?php

/**
 * This is the model base class for the table "Usuario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Usuario".
 *
 * Columns in table "Usuario" available as properties of the model,
 * followed by relations of table "Usuario" available as properties of the model.
 *
 * @property string $id
 * @property string $usuario
 * @property string $password
 * @property string $tipousuario_did
 * @property string $estatus_did
 * @property string $fechaCreacion
 *
 * @property Gasto[] $gastos
 * @property Persona[] $personas
 * @property Presupuesto[] $presupuestos
 * @property Estatus $estatus
 * @property TipoUsuario $tipousuario
 */
abstract class BaseUsuario extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'Usuario';
    }

    public static function representingColumn() {
        return 'usuario';
    }

    public function rules() {
        return array(
            array('tipousuario_did, estatus_did', 'required'),
            array('usuario, password', 'length', 'max'=>100),
            array('tipousuario_did', 'length', 'max'=>11),
            array('estatus_did', 'length', 'max'=>10),
            array('fechaCreacion', 'safe'),
            array('usuario, password, fechaCreacion', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, usuario, password, tipousuario_did, estatus_did, fechaCreacion', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'gastos' => array(self::HAS_MANY, 'Gasto', 'usuario_did'),
            'personas' => array(self::HAS_MANY, 'Persona', 'usuario_did'),
            'presupuestos' => array(self::HAS_MANY, 'Presupuesto', 'usuario_did'),
            'estatus' => array(self::BELONGS_TO, 'Estatus', 'estatus_did'),
            'tipousuario' => array(self::BELONGS_TO, 'TipoUsuario', 'tipousuario_did'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'usuario' => Yii::t('app', 'Usuario'),
                'password' => Yii::t('app', 'Password'),
                'tipousuario_did' => Yii::t('app', 'Tipousuario Did'),
                'estatus_did' => Yii::t('app', 'Estatus Did'),
                'fechaCreacion' => Yii::t('app', 'Fecha Creacion'),
                'gastos' => null,
                'personas' => null,
                'presupuestos' => null,
                'estatus' => null,
                'tipousuario' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id, true);
        $criteria->compare('usuario', $this->usuario, true);
        $criteria->compare('password', $this->password, true);
        $criteria->compare('tipousuario_did', $this->tipousuario_did);
        $criteria->compare('estatus_did', $this->estatus_did);
        $criteria->compare('fechaCreacion', $this->fechaCreacion, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}